export const SCAN_PRODUCT_TAG_ACTION = 'SCAN_PRODUCT_TAG_ACTION';
export const LOG_IN_ACTION = 'LOG_IN_ACTION';
export const SIGN_UP_ACTION = 'SIGN_UP_ACTION';

export const FETCH_PRODUCER_DATA_ACTION = 'FETCH_PRODUCER_DATA_ACTION';
export const SET_PRODUCER_DATA_ACTION = 'SET_PRODUCER_DATA_ACTION';

export const FETCH_SIGN_UP_FORM_DATA_ACTION = 'FETCH_SIGN_UP_FORM_DATA_ACTION';
export const FETCH_PT_BY_HASH_ACTION = 'FETCH_PT_BY_HASH_ACTION';
export const SET_FETCHED_PT_ACTION = 'SET_FETCHED_PT_ACTION';
export const PT_DOES_NOT_EXIST_ACTION = 'PT_DOES_NOT_EXIST_ACTION';
export const SET_SIGN_UP_FORM_INIT_DATA_ACTION = 'SET_SIGN_UP_FORM_INIT_DATA_ACTION';
export const CHANGE_LANGUAGE_ACTION = 'CHANGE_LANGUAGE_ACTION';
// export const SET_PRODUCT_TAG_ACTION = 'SET_PRODUCT_TAG_ACTION';
export const UI_START_LOADING_ACTION = 'UI_START_LOADING_ACTION';
export const UI_STOP_LOADING_ACTION = 'UI_STOP_LOADING_ACTION';
export const AUTH_SET_JWT_TOKEN_ACTION = 'AUTH_SET_JWT_TOKEN_ACTION';
export const OPEN_PT_MAP_VIEW_MODAL_ACTION = 'OPEN_PT_MAP_VIEW_MODAL_ACTION';
export const CLOSE_PT_MAP_VIEW_MODAL_ACTION = 'CLOSE_PT_MAP_VIEW_MODAL_ACTION';
export const OPEN_QR_CODE_SCANNER_ACTION = 'OPEN_QR_CODE_SCANNER_ACTION';
export const CLOSE_QR_CODE_SCANNER_ACTION = 'CLOSE_QR_CODE_SCANNER_ACTION';

export const OPEN_QR_SCANNER_MODAL_ACTION = 'OPEN_QR_SCANNER_MODAL_ACTION';
export const CLOSE_QR_SCANNER_MODAL_ACTION = 'CLOSE_QR_SCANNER_MODAL_ACTION';
export const OPEN_MAP_VIEW_MODAL_ACTION = 'OPEN_MAP_VIEW_MODAL_ACTION';
export const CLOSE_MAP_VIEW_MODAL_ACTION = 'CLOSE_MAP_VIEW_MODAL_ACTION';
export const SET_PT_FOR_MAP_VIEW_ACTION = 'SET_PT_FOR_MAP_VIEW_ACTION';

export const SCANNED_PT_VALID_ACTION = 'SCANNED_PT_VALID_ACTION';
// export const SCANNED_PT_ALREADY_SCANNED_ACTION = 'SCANNED_PT_ALREADY_SCANNED_ACTION';
export const OPEN_ALERT_ON_SCAN_ACTION = 'OPEN_ALERT_ON_SCAN_ACTION';
export const CLOSE_ALERT_ON_SCAN_ACTION = 'CLOSE_ALERT_ON_SCAN_ACTION';
export const SET_PRODUCER_SCANNED_PT_ACTION = 'SET_PRODUCER_SCANNED_PT_ACTION';

export const SET_CONSUMER_SCANNED_PT_ACTION = 'SET_CONSUMER_SCANNED_PT_ACTION';

export const PREPARE_STATE_FOR_QR_SCANNER_SCREEN_ACTION = 'PREPARE_STATE_FOR_QR_SCANNER_SCREEN_ACTION';