export default {
    BACKEND_BASE_URL: 'https://foodchain-csg.ch',
    GENESIS_PRODUCT_TAG_HASH_VALUE: '0',
    FOODCHAIN_WEB3J_RINKEBY_HTTPSERVICE_URL: '',
    FOODCHAIN_CONTRACT_ADDRESS: '',
    FOODCHAIN_ACCOUNT_PRIVATEKEY: '',
    FOODCHAIN_ETH_WALLET_MNOMENIC: '',
    mode: {
        'PRODUCER': 'PRODUCER',
        'CONSUMER': 'CONSUMER'
    }
};
